import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body className={inter.className}>
      <header style={{backgroundColor:'lightblue',padding:"1rem",}}>
        <p>header section</p>
      </header>{children}
       
      </body>
      <footer style={{backgroundColor:'yellow',padding:"1rem",}}>Footer section</footer>
    </html>
  );
}
